Repository collaborationFactory/cplace-asc, pull requests merged in 2022-09, with the labels that each got.

#85 PFM-ISSUE-10841 - Set NODE_ENV production from cplace-asc
  src/compiler/VendorCompiler.ts
  src/index.ts
Labels: PR: Needs Review

#87 PFM-ISSUE-10987: cplace-asc fails when running with --production
  src/index.ts
Labels: bug, PR: Needs Review

#88 PFM-ISSUE-10984 - Run combineJavascript in cplace-asc GHA
  .github/pull_request_template.yaml
  .github/workflows/continuous-integration.yml
  npm-shrinkwrap.json
  package.json
  src/compiler/CombineJavascriptsCompiler.ts
  src/compiler/CplaceTypescriptCompiler.ts
  src/compiler/VendorCompiler.ts
  src/compiler/index.ts
  src/executor/JobTracker.ts
  src/executor/Scheduler.ts
  src/index.ts
  src/model/AssetsCompiler.ts
  src/model/CplacePlugin.ts
  src/model/DescriptorParser.ts
  src/model/ImlDescriptorParser.ts
  src/model/PluginDescriptor.ts
  src/model/PluginDescriptorParser.ts
  src/model/RegistryInitializer.ts
  src/model/utils.ts
  test/NPMResolver.test.ts
  test/PluginDescriptor.test.ts
  test/RegistryInitializer.test.ts
  test/helper/TestHelpers.ts
Labels: PR: Needs Review

#89 PFM-ISSUE-10996: cplace-asc check if node_modules exist before deleting it
  npm-shrinkwrap.json
  package.json
  src/model/NPMResolver.ts
Labels: bug
