Repository collaborationFactory/cplace-asc, pull requests merged in 2023-11, with the labels that each got.

#121 PFM-ISSUE-25046: rework cplace version calculation
  npm-shrinkwrap.json
  package.json
  src/model/CplaceVersion.ts
  test/CplaceVersion.test.ts
  test/PluginDescriptor.test.ts
  test/helper/TestHelpers.ts
Labels: bug, PR: Needs Review

#123 PFM-ISSUE-25046: rework cplace version calculation v2.x.x
  package-lock.json
  package.json
  src/model/CplaceVersion.ts
  test/CplaceVersion.test.ts
  test/PluginDescriptor.test.ts
  test/helper/TestHelpers.ts
Labels: bug, PR: Needs Review

#122 PFM-TASK-4114 - Adjust cplace-asc to use newest Node 18
  .github/workflows/continuous_integration.yml
  .github/workflows/push_master.yml
  .github/workflows/push_release.yml
  .github/workflows/push_tag.yml
  .nvmrc
  .tool-versions
  package-lock.json
  package.json
  src/model/SupportedNodeVersion.ts
  tools/asc-local-migration/asc-2-asc-local.ts
Labels: Test: Successful, PR: Needs Review

#124 PFM-ISSUE-25124: Fix reading the version file
  npm-shrinkwrap.json
  package.json
  src/index.ts
  src/model/AbstractPackageJsonGenerator.ts
  src/model/CplaceVersion.ts
Labels: bug, PR: Needs Review

#126 PFM-ISSUE-25124: Fix reading of version file - v2.1.x
  package-lock.json
  package.json
  src/model/AbstractPackageJsonGenerator.ts
  src/model/CplaceVersion.ts
Labels: bug, PR: Needs Review

#129 bumped version
  package-lock.json
  package.json
Labels: PR: Needs Review

#128 PFM-ISSUE-25234 update cplace asc notification or consider 2.1.x
  .github/workflows/continuous_integration.yml
  package-lock.json
  package.json
  src/executor/Scheduler.ts
  src/index.ts
  src/model/AssetsCompiler.ts
  src/utils/check-update.ts
  src/utils/index.ts
Labels: Test: Successful, PR: Needs Review
