Repository collaborationFactory/cplace-asc, pull requests merged in 2023-03, with the labels that each got.

#105 PFM-ISSUE-12143 accept node 12 in cplace asc for releases <= 5.18
  npm-shrinkwrap.json
  package.json
  src/index.ts
Labels: PR: In Review

#106 PFM-ISSUE-12154 - Endless loop in cplace-asc local @2.0.11
  README.md
  package-lock.json
  package.json
  src/compiler/VendorCompiler.ts
  src/index.ts
  src/model/NPMResolver.ts
  src/utils/check-update.ts
Labels: Test: Successful, PR: Needs Review

#107 PFM-ISSUE-12218 - Fix package-lock hash
  package-lock.json
  package.json
  src/model/NPMResolver.ts
Labels: PR: Needs Review
