Repository collaborationFactory/cplace-asc, pull requests merged in 2023-02, with the labels that each got.

#99 PFM-TASK-3316 - Check node version with @cplace/asc-local
  .github/workflows/continuous_integration.yml
  package-lock.json
  package.json
  src/compiler/CombineJavascriptCompiler.ts
  src/index.ts
  src/model/AbstractNodeVersion.ts
  src/model/AssetsCompiler.ts
  src/model/ProcessNodeVersion.ts
  src/model/SupportedNodeVersion.ts
  src/utils/NodeUtils.ts
  test/PluginDescriptor.test.ts
Labels: Test: Required, PR: Needs Review

#102 PFM-TASK-3357 - Fix @cplace/asc-local error handling
  .github/workflows/continuous_integration.yml
  package-lock.json
  package.json
  src/executor/ExecutorService.ts
  src/index.ts
  src/model/AssetsCompiler.ts
  src/model/NPMResolver.ts
Labels: Test: Required, PR: Needs Review

#98 PFM-TASK-3315 - Check node version with @cplace/asc
  npm-shrinkwrap.json
  package.json
  src/executor/ExecutorService.ts
  src/index.ts
  src/model/AbstractNodeVersion.ts
  src/model/AssetsCompiler.ts
  src/model/ProcessNodeVersion.ts
  src/model/SupportedNodeVersion.ts
  src/utils/NodeUtils.ts
  test/PluginDescriptor.test.ts
Labels: Test: Required, PR: Needs Review

#104 PFM-ISSUE-12092 allow all node versions for release 5 12 legacy asc
  .github/workflows/continuous-integration.yml
  npm-shrinkwrap.json
  package.json
  src/index.ts
  src/utils/NodeUtils.ts
Labels: PR: Needs Review

#103 PFM-ISSUE-12085: Fix npm publishing scope in cplace-asc-local
  .github/workflows/continuous_integration.yml
  package-lock.json
  package.json
  src/model/AbstractPackageJsonGenerator.ts
  src/model/PluginPackageJsonGenerator.ts
  test/PackageJsonGenerator.test.ts
Labels: bug, PR: Needs Review
